apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: pod2
  name: pod2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: pod2
  type: NodePort
status:
  loadBalancer: {}
