---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: anand-role
  namespace: development
rules:
  - apiGroups: ["", "extensions", "apps", "networking.k8s.io"] # "" indicates the core API group for echo use '' not "".
    resources: ["pods", "deployments","replicasets", "services", "ingresses", "secrets"]
    verbs: ["get", "update", "list", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bala-role
  namespace: production
rules:
  - apiGroups: ["", "extensions", "apps", "networking.k8s.io"] # "" indicates the core API group for echo use '' not "".
    resources: ["pods", "deployments","replicasets", "services", "ingresses", "secrets"]
    verbs: ["get", "update", "list", "create", "delete"]