# PriorityClass for normal applications
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: normal-apps
value: 100
globalDefault: false
preemptionPolicy: PreemptLowerPriority
description: "Priority class for normal applications."