apiVersion: v1
kind: Service
metadata:
  labels:
    run: testpod2
  name: testpod2
spec:
  containers:
  - image: nginx:latest
    name: testpod2
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: testpod2

