---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anand-RoleBinding
  namespace: development
subjects:
- kind: User
  name: anand
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: anand-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bala-RoleBinding
  namespace: production
subjects:
- kind: User
  name: bala
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: bala-role
  apiGroup: rbac.authorization.k8s.io
