---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: development
spec:
  hard:
    #compute-resources
    requests.cpu: "1000m"
    limits.cpu: "2000m"
    requests.memory: "1Gi"
    limits.memory: "2Gi"
    #object-counts
    pods: "4"
    replicationcontrollers: "20"
    resourcequotas: "10"
    services: "5"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: development
spec:
  hard:
    count/deployment.apps: "1"
    count/pods: "4"
    count/replicasets.apps: "4"
    count/secrets: "4"
    count/services: "1"
